version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  #app:
  #  build: .
  #  ports:
  #    - "8000:8000"
  #  environment:
  #    DATABASE_URL: postgresql://user:password@postgres:5432/fastapi_db
  #  depends_on:
  #    - postgres
  #  volumes:
  #    - .:/app
  #  command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: